# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Stock', models.IntegerField()),
                ('StockMinimo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='UnidadId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Unidad'),
        ),
    ]
