# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='UnidadId',
            new_name='Unidad',
        ),
    ]
