# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20170802_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=15)),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Empresa')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name_plural': 'Unidades'},
        ),
    ]
